version: "3.9"
services:
  web:
    image: nginx 
    container_name: my-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # 改为自己的证书地址
      - /etc/letsencrypt/live/music.xhyh.site/fullchain.pem:/etc/nginx/certs/music/fullchain.pem:ro
      - /etc/letsencrypt/live/music.xhyh.site/chain.pem:/etc/nginx/certs/music/chain.pem:ro
      - /etc/letsencrypt/live/music.xhyh.site/privkey.pem:/etc/nginx/certs/music/privkey.pem:ro
      - ./nginx-data/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-data/music.conf:/etc/nginx/conf.d/music.conf:ro
      - ./nginx-data/dhparams.pem:/etc/nginx/dhparams.pem:ro
    restart: unless-stopped

networks:
  default:
    external:
      name: webproxy   